version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/ruby/Dockerfile
    command: docker/ruby/entrypoint.sh
    volumes:
      - .:/app
      - bundle:/bundle
      - public-files:/app/public
    env_file: .env
    stdin_open: true
    tty: true
    networks:
      - demo_docker
  sidekiq:
    build:
      context: .
      dockerfile: docker/ruby/Dockerfile
    command: docker/common/wait-for-it.sh redis:6379 -- bundle exec sidekiq
    depends_on:
      - app
      - redis
    volumes:
      - .:/app
      - bundle:/bundle
    env_file: .env
    networks:
      - demo_docker
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "${NGINX_SERVER_PORT}:80"
    env_file: .env
    networks:
      - demo_docker
    volumes:
      - "${PROJECT_LOG_PATH}:/app/log"
      - public-files:/app/public
  redis:
    image: redis:5.0.3
    volumes:
      - redis-data:/data
    networks:
      - demo_docker
volumes:
  bundle:
  public-files:
  redis-data:
networks:
  demo_docker:
    external:
      name: demo_docker
