version: "3"

services:
  db:
    image: mysql:8.0.13
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    env_file: .env
    networks:
      - demo_docker
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: docker/common/wait-for-it.sh db:3306 -- docker/app/entrypoint.sh
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - 3000:3000
    env_file: .env
    stdin_open: true
    tty: true
    networks:
      - demo_docker
volumes:
  db-data:
  bundle:
networks:
  demo_docker:
    external:
      name: demo_docker
