version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: docker/app/entrypoint.sh
    volumes:
      - .:/app
      - bundle:/bundle
      - public-files:/app/public
    env_file: .env
    stdin_open: true
    tty: true
    networks:
      - demo_docker
  sidekiq:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: docker/common/wait-for-it.sh app:3000 -- bundle exec sidekiq
    volumes:
      - .:/app
      - bundle:/bundle
    env_file: .env
    networks:
      - demo_docker
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - "${NGINX_SERVER_PORT}:80"
    env_file: .env
    networks:
      - demo_docker
    volumes:
      - "${PROJECT_LOG_PATH}:/api/log"
      - public-files:/nginx/public
volumes:
  bundle:
  public-files:
networks:
  demo_docker:
    external:
      name: demo_docker
